"""Read-only source connectors and their independently verifiable captures."""

from assurance_lab.connectors.contract import (
    ConnectorCapture,
    ConnectorCaptureError,
    ConnectorDescriptor,
    ConnectorWindow,
    VerifiedConnectorCapture,
)
from assurance_lab.connectors.defender_xdr import (
    DefenderBearerToken,
    DefenderBearerTokenProvider,
    DefenderXDRConnector,
    DefenderXDRRequest,
    defender_xdr_endpoint_origin_digest,
    new_defender_capture_nonce,
    verify_defender_xdr_capture,
)
from assurance_lab.connectors.elastic_security import (
    ElasticApiKey,
    ElasticSecurityConnector,
    ElasticSecurityRequest,
    elastic_endpoint_origin_digest,
    new_capture_nonce,
    verify_elastic_security_capture,
)
from assurance_lab.connectors.evidence import (
    ConnectorEvidenceBundle,
    ConnectorEvidenceError,
    ConnectorEvidenceJob,
    VerifiedConnectorEvidenceBundle,
    connector_request_bytes,
    create_connector_evidence_job,
    verify_connector_evidence_bundle,
    write_connector_evidence_bundle,
)
from assurance_lab.connectors.managed_evidence import (
    ManagedAuthorizationProfile,
    ManagedConnectorEvidenceBundle,
    ManagedConnectorEvidenceError,
    ManagedConnectorEvidenceJob,
    PamReceiptVerificationContext,
    PamReceiptVerifier,
    VerifiedManagedConnectorEvidenceBundle,
    VerifiedPamLifecycleReceipt,
    create_managed_connector_evidence_job,
    managed_connector_request_bytes,
    verify_streamed_managed_connector_evidence_bundle,
    write_managed_connector_evidence_bundle,
)
from assurance_lab.connectors.secret_profiles import (
    ELASTIC_PARENT_CREDENTIAL_CONTENT_TYPE,
    ELASTIC_PARENT_CREDENTIAL_SCHEMA_VERSION,
    ConnectorSecretProfileError,
    decode_elastic_parent_credential,
)

__all__ = [
    "ELASTIC_PARENT_CREDENTIAL_CONTENT_TYPE",
    "ELASTIC_PARENT_CREDENTIAL_SCHEMA_VERSION",
    "ConnectorCapture",
    "ConnectorCaptureError",
    "ConnectorDescriptor",
    "ConnectorEvidenceBundle",
    "ConnectorEvidenceError",
    "ConnectorEvidenceJob",
    "ConnectorSecretProfileError",
    "ConnectorWindow",
    "DefenderBearerToken",
    "DefenderBearerTokenProvider",
    "DefenderXDRConnector",
    "DefenderXDRRequest",
    "ElasticApiKey",
    "ElasticSecurityConnector",
    "ElasticSecurityRequest",
    "ManagedAuthorizationProfile",
    "ManagedConnectorEvidenceBundle",
    "ManagedConnectorEvidenceError",
    "ManagedConnectorEvidenceJob",
    "PamReceiptVerificationContext",
    "PamReceiptVerifier",
    "VerifiedConnectorCapture",
    "VerifiedConnectorEvidenceBundle",
    "VerifiedManagedConnectorEvidenceBundle",
    "VerifiedPamLifecycleReceipt",
    "connector_request_bytes",
    "create_connector_evidence_job",
    "create_managed_connector_evidence_job",
    "decode_elastic_parent_credential",
    "defender_xdr_endpoint_origin_digest",
    "elastic_endpoint_origin_digest",
    "managed_connector_request_bytes",
    "new_capture_nonce",
    "new_defender_capture_nonce",
    "verify_connector_evidence_bundle",
    "verify_defender_xdr_capture",
    "verify_elastic_security_capture",
    "verify_streamed_managed_connector_evidence_bundle",
    "write_connector_evidence_bundle",
    "write_managed_connector_evidence_bundle",
]
